"""Custom roles system

Revision ID: b85686132756
Revises: 
Create Date: 2026-03-24 23:40:56.181435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b85686132756'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('permissions_json', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_membership_role_id', 'club_roles', ['role_id'], ['id'])

    with op.batch_alter_table('poll_votes', schema=None) as batch_op:
        batch_op.drop_constraint('unique_vote_per_option', type_='unique')
        batch_op.create_unique_constraint('unique_vote_per_poll', ['poll_id', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll_votes', schema=None) as batch_op:
        batch_op.drop_constraint('unique_vote_per_poll', type_='unique')
        batch_op.create_unique_constraint('unique_vote_per_option', ['option_id', 'user_id'])

    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_constraint('fk_membership_role_id', type_='foreignkey')
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('role_id')

    op.drop_table('club_roles')
    # ### end Alembic commands ###
